#!/bin/bash

set -euo pipefail
 
modprobe vfio-pci
 
for grp 
do
	for dev in /sys/kernel/iommu_groups/$grp/devices/*
	do
		if [ -e $dev/driver ]
		then
			echo $(basename $dev) > $dev/driver/unbind
		fi
		echo vfio-pci > $dev/driver_override
		echo $(basename $dev) > /sys/bus/pci/drivers_probe
	done
done

